apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: order-service
data:
  APP_PORT: "3001"
  NODE_ENV: "production"
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_USER: "order_service"
  DATABASE_NAME: "order_service"
  CUSTOMER_SERVICE_URL: "http://customer-service:3002"
  CUSTOMER_SERVICE_TIMEOUT: "3000"
  CUSTOMER_SERVICE_RETRIES: "1"
  NEW_RELIC_APP_NAME: "order-service"
  ENABLE_NEW_RELIC: "false"
  ENABLE_PAYMENT_CONSUMER: "true"

